Repository AY2223S2-CS2103T-T17-2/tp, pull requests merged in 2023-03, with the labels that each got.

#92 Branch department update
  src/main/java/seedu/sudohr/commons/core/Messages.java
  src/main/java/seedu/sudohr/logic/commands/EditCommand.java
  src/main/java/seedu/sudohr/logic/commands/EditDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/parser/EditDepartmentCommandParser.java
  src/main/java/seedu/sudohr/logic/parser/ParserUtil.java
  src/main/java/seedu/sudohr/logic/parser/SudoHrParser.java
  src/main/java/seedu/sudohr/model/Model.java
  src/main/java/seedu/sudohr/model/ModelManager.java
  src/main/java/seedu/sudohr/model/SudoHr.java
  src/main/java/seedu/sudohr/model/department/UniqueDepartmentList.java
  src/test/java/seedu/sudohr/logic/commands/AddCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/AddDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/CommandTestUtil.java
  src/test/java/seedu/sudohr/logic/commands/EditDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/parser/EditDepartmentCommandParserTest.java
  src/test/java/seedu/sudohr/testutil/EditDepartmentDescriptorBuilder.java
  src/test/java/seedu/sudohr/testutil/TypicalDepartmentNames.java
Labels: type.Story, priority.High

#93 Update code to enforce identities check
  src/main/java/seedu/sudohr/logic/commands/AddCommand.java
  src/main/java/seedu/sudohr/logic/commands/ClearCommand.java
  src/main/java/seedu/sudohr/logic/commands/DeleteCommand.java
  src/main/java/seedu/sudohr/logic/commands/EditCommand.java
  src/main/java/seedu/sudohr/logic/parser/CliSyntax.java
  src/main/java/seedu/sudohr/model/Model.java
  src/main/java/seedu/sudohr/model/ModelManager.java
  src/main/java/seedu/sudohr/model/SudoHr.java
  src/main/java/seedu/sudohr/model/employee/Employee.java
  src/main/java/seedu/sudohr/model/employee/UniqueEmployeeList.java
  src/main/java/seedu/sudohr/model/employee/exceptions/DuplicateEmailException.java
  src/main/java/seedu/sudohr/model/employee/exceptions/DuplicateEmployeeException.java
  src/main/java/seedu/sudohr/model/employee/exceptions/DuplicatePhoneNumberException.java
  src/main/java/seedu/sudohr/model/util/SampleDataUtil.java
  src/main/java/seedu/sudohr/storage/JsonSerializableSudoHr.java
  src/test/data/JsonSerializableSudoHrTest/duplicateEmailSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/duplicateIdSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/duplicatePhoneEmailSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/duplicatePhoneSudoHr.json
  src/test/java/seedu/sudohr/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/sudohr/logic/commands/AddCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/AddDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/EditCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/sudohr/model/ModelManagerTest.java
  src/test/java/seedu/sudohr/model/SudoHrTest.java
  src/test/java/seedu/sudohr/model/person/PersonTest.java
  src/test/java/seedu/sudohr/model/person/UniquePersonListTest.java
  src/test/java/seedu/sudohr/storage/JsonSerializableSudoHrTest.java
  src/test/java/seedu/sudohr/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#103 implement addleave and delete leave
  .gitignore
  src/main/java/seedu/sudohr/MainApp.java
  src/main/java/seedu/sudohr/commons/core/Messages.java
  src/main/java/seedu/sudohr/logic/commands/DeleteCommand.java
  src/main/java/seedu/sudohr/logic/commands/leaveCommands/AddEmployeeToLeaveCommand.java
  src/main/java/seedu/sudohr/logic/commands/leaveCommands/DeleteEmployeeFromLeaveCommand.java
  src/main/java/seedu/sudohr/logic/commands/leaveCommands/ListEmployeeInLeaveCommand.java
  src/main/java/seedu/sudohr/logic/parser/AddEmployeeToLeaveCommandParser.java
  src/main/java/seedu/sudohr/logic/parser/CliSyntax.java
  src/main/java/seedu/sudohr/logic/parser/DeleteEmployeeFromLeaveCommandParser.java
  src/main/java/seedu/sudohr/logic/parser/ListEmployeeInLeaveCommandParser.java
  src/main/java/seedu/sudohr/logic/parser/ParserUtil.java
  src/main/java/seedu/sudohr/logic/parser/SudoHrParser.java
  src/main/java/seedu/sudohr/model/Model.java
  src/main/java/seedu/sudohr/model/ModelManager.java
  src/main/java/seedu/sudohr/model/ReadOnlySudoHr.java
  src/main/java/seedu/sudohr/model/SudoHr.java
  src/main/java/seedu/sudohr/model/department/exceptions/DuplicateDepartmentException.java
  src/main/java/seedu/sudohr/model/leave/Date.java
  src/main/java/seedu/sudohr/model/leave/Leave.java
  src/main/java/seedu/sudohr/model/leave/LeaveContainsEmployeePredicate.java
  src/main/java/seedu/sudohr/model/leave/UniqueLeaveList.java
  src/main/java/seedu/sudohr/model/leave/exceptions/DuplicateLeaveException.java
  src/main/java/seedu/sudohr/model/leave/exceptions/LeaveNotFoundException.java
  src/main/java/seedu/sudohr/model/util/SampleDataUtil.java
  src/main/java/seedu/sudohr/storage/JsonAdaptedLeave.java
  src/main/java/seedu/sudohr/storage/JsonSerializableSudoHr.java
  src/main/java/seedu/sudohr/ui/CommandBox.java
  src/test/data/JsonSerializableSudoHrTest/clashingEmployeeEmailInDepartmentSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/clashingEmployeeIdInDepartmentSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/clashingEmployeePhoneInDepartmentSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/duplicateDepartmentSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/duplicateEmailSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/duplicateEmployeeInDepartmentSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/duplicateEmployeeSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/duplicateIdSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/duplicatePhoneEmailSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/duplicatePhoneSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/invalidDepartmentSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/invalidEmployeeSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/nonExistentEmployeeInDepartmentSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/typicalDepartmentsSudoHr.json
  src/test/data/JsonSerializableSudoHrTest/typicalEmployeesSudoHr.json
  src/test/data/JsonSudoHrStorageTest/invalidAndValidDepartmentSudoHr.json
  src/test/data/JsonSudoHrStorageTest/invalidAndValidEmployeeSudoHr.json
  src/test/data/JsonSudoHrStorageTest/invalidDepartmentSudoHr.json
  src/test/data/JsonSudoHrStorageTest/invalidEmployeeSudoHr.json
  src/test/java/seedu/sudohr/logic/commands/AddCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/AddDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/AddEmployeeToDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/sudohr/model/SudoHrTest.java
Labels: type.Story, priority.High

#107 Branch delete department mergeable
  src/main/java/seedu/sudohr/logic/commands/department/DeleteDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/employee/DeleteCommand.java
  src/main/java/seedu/sudohr/logic/parser/DeleteDepartmentCommandParser.java
  src/main/java/seedu/sudohr/logic/parser/SudoHrParser.java
  src/test/java/seedu/sudohr/logic/commands/DeleteDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/employee/DeleteCommandTest.java
  src/test/java/seedu/sudohr/logic/parser/DeleteDepartmentCommandParserTest.java
  src/test/java/seedu/sudohr/testutil/TypicalDepartmentNames.java
  src/test/java/seedu/sudohr/testutil/TypicalDepartments.java
Labels: type.Story, priority.High

#134 Support listing of employees in a given department
  src/main/java/seedu/sudohr/logic/commands/department/ListEmployeesInDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/parser/SudoHrParser.java
  src/main/java/seedu/sudohr/logic/parser/department/ListEmployeesInDepartmentCommandParser.java
  src/test/java/seedu/sudohr/logic/commands/department/ListEmployeesInDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/parser/department/ListEmployeesInDepartmentCommandParserTest.java
  src/test/java/seedu/sudohr/testutil/TypicalDepartmentNames.java
  src/test/java/seedu/sudohr/testutil/TypicalDepartments.java
Labels: type.Story, priority.High

#135 Cascade delete and edit commands for employee to departments and leave
  src/main/java/seedu/sudohr/logic/commands/employee/DeleteCommand.java
  src/main/java/seedu/sudohr/logic/commands/employee/EditCommand.java
  src/main/java/seedu/sudohr/model/Model.java
  src/main/java/seedu/sudohr/model/ModelManager.java
  src/main/java/seedu/sudohr/model/SudoHr.java
  src/main/java/seedu/sudohr/model/department/Department.java
  src/main/java/seedu/sudohr/model/leave/Leave.java
  src/main/java/seedu/sudohr/model/leave/UniqueLeaveList.java
  src/test/java/seedu/sudohr/logic/commands/department/AddDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/department/AddEmployeeToDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/department/RemoveEmployeeFromDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/employee/AddCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/employee/DeleteCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/employee/EditCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/leave/AddEmployeeToLeaveCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/leave/DeleteEmployeeFromLeaveCommandTest.java
  src/test/java/seedu/sudohr/model/department/DepartmentTest.java
  src/test/java/seedu/sudohr/testutil/TypicalDepartments.java
  src/test/java/seedu/sudohr/testutil/TypicalEmployees.java
  src/test/java/seedu/sudohr/testutil/TypicalLeave.java
Labels: priority.High, severity.High

#152 List Leaves Command
  build.gradle
  src/main/java/seedu/sudohr/logic/commands/department/ListDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/leave/ListLeaveCommand.java
  src/main/java/seedu/sudohr/logic/parser/SudoHrParser.java
  src/main/java/seedu/sudohr/model/Model.java
  src/main/java/seedu/sudohr/model/ModelManager.java
  src/main/java/seedu/sudohr/model/employee/UniqueEmployeeList.java
  src/main/java/seedu/sudohr/model/leave/Leave.java
  src/test/java/seedu/sudohr/logic/commands/department/EditDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/department/ListDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/department/ListEmployeeDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/department/ListEmployeesInDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/employee/ListCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/leave/ListLeaveCommandTest.java
  src/test/java/seedu/sudohr/testutil/DepartmentBuilder.java
Labels: type.Story, priority.High

#153 Fix test issues
  src/test/java/seedu/sudohr/logic/commands/department/EditDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/department/ListEmployeeDepartmentCommandTest.java
  src/test/java/seedu/sudohr/logic/commands/department/ListEmployeesInDepartmentCommandTest.java
Labels: priority.High, type.Task

#154 Update developer guide for my commands (Department)
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/commands/department/AddDepartmentActivityDiagram.puml
  docs/diagrams/commands/department/AddDepartmentSequenceDiagram.puml
  docs/diagrams/commands/department/AddEmployeeToDepartmentActivityDiagram.puml
  docs/diagrams/commands/department/AddEmployeeToDepartmentSequenceDiagram.puml
  docs/diagrams/commands/department/DeleteDepartmentActivityDiagram.puml
  docs/diagrams/commands/department/DeleteDepartmentSequenceDiagram.puml
  docs/diagrams/commands/department/DepartmentModelClassDiagram.puml
  docs/diagrams/commands/department/EditDepartmentActivityDiagram.puml
  docs/diagrams/commands/department/EditDepartmentSequenceDiagram.puml
  docs/diagrams/commands/department/ListEmployeeDepartmentActivityDiagram.puml
  docs/diagrams/commands/department/ListEmployeeDepartmentSequenceDiagram.puml
  docs/diagrams/commands/department/RemoveEmployeeFromDepartmentActivityDiagram.puml
  docs/diagrams/commands/department/RemoveEmployeeFromDepartmentSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/commands/department/AddDepartmentActivityDiagram.png
  docs/images/commands/department/AddDepartmentSequenceDiagram.png
  docs/images/commands/department/AddEmployeeToDepartmentActivityDiagram.png
  docs/images/commands/department/AddEmployeeToDepartmentSequenceDiagram.png
  docs/images/commands/department/DeleteDepartmentActivityDiagram.png
  docs/images/commands/department/DeleteDepartmentSequenceDiagram.png
  docs/images/commands/department/DepartmentModelClassDiagram.png
  docs/images/commands/department/EditDepartmentActivityDiagram.png
  docs/images/commands/department/EditDepartmentSequenceDiagram.png
  docs/images/commands/department/ListEmployeeDepartmentActivityDiagram.png
  docs/images/commands/department/ListEmployeeDepartmentSequenceDiagram.png
  docs/images/commands/department/RemoveEmployeeFromDepartmentActivityDiagram.png
  docs/images/commands/department/RemoveEmployeeFromDepartmentSequenceDiagram.png
  src/main/java/seedu/sudohr/logic/commands/department/AddDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/department/AddEmployeeToDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/department/DeleteDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/department/EditDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/department/ListEmployeeDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/department/ListEmployeesInDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/department/RemoveEmployeeFromDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/parser/department/DeleteDepartmentCommandParser.java
  src/main/java/seedu/sudohr/logic/parser/department/ListEmployeesInDepartmentCommandParser.java
  src/main/java/seedu/sudohr/logic/parser/department/RemoveEmployeeFromDepartmentCommandParser.java
Labels: type.Documentation, priority.High

#166 Update user guide (Departments)
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#178 Fix command names, output, etc
  docs/UserGuide.md
  src/main/java/seedu/sudohr/logic/commands/department/AddDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/department/EditDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/department/ListDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/department/ListEmployeeDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/department/ListEmployeesInDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/employee/DeleteCommand.java
  src/main/java/seedu/sudohr/logic/commands/leave/AddEmployeeToLeaveCommand.java
  src/main/java/seedu/sudohr/logic/commands/leave/AddEmployeeToLeaveFromToCommand.java
  src/main/java/seedu/sudohr/logic/commands/leave/DeleteEmployeeFromLeaveCommand.java
  src/main/java/seedu/sudohr/logic/commands/leave/ListEmployeeInLeaveCommand.java
  src/test/java/seedu/sudohr/logic/LogicManagerTest.java
Labels: priority.High, type.Task

#205 Fix remaining bugs
  src/main/java/seedu/sudohr/logic/commands/employee/DeleteCommand.java
  src/main/java/seedu/sudohr/logic/commands/employee/EditCommand.java
  src/main/java/seedu/sudohr/model/SudoHr.java
Labels: priority.High, type.Bug, severity.High

#207 Implement find employee by id command
  src/main/java/seedu/sudohr/commons/core/Messages.java
  src/main/java/seedu/sudohr/logic/commands/department/EditDepartmentCommand.java
  src/main/java/seedu/sudohr/logic/commands/employee/FindByIdCommand.java
  src/main/java/seedu/sudohr/logic/commands/employee/ListCommand.java
  src/main/java/seedu/sudohr/logic/parser/SudoHrParser.java
  src/main/java/seedu/sudohr/logic/parser/employee/FindByIdCommandParser.java
  src/main/java/seedu/sudohr/logic/parser/employee/FindCommandParser.java
  src/main/java/seedu/sudohr/model/employee/Employee.java
  src/main/java/seedu/sudohr/model/employee/FindByIdPredicate.java
  src/main/java/seedu/sudohr/model/employee/NameContainsKeywordsPredicate.java
Labels: priority.High, type.Enhancement

#208 Update help command
  docs/UserGuide.md
  src/main/java/seedu/sudohr/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High, type.Task

#209 Update general ug
  docs/UserGuide.md
  docs/_includes/toc.html
  docs/images/Ui.png
  docs/images/UiPreview.png
  docs/images/commandFormat.png
  src/main/java/seedu/sudohr/model/employee/Employee.java
  src/main/java/seedu/sudohr/ui/HelpWindow.java
Labels: type.Documentation, priority.High
